services:
  web:
    build: .
    container_name: kahadia2_web
    command: ["npm","run","start","--","-H","0.0.0.0","-p","3000"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  api:
    build: .
    container_name: kahadia2_api
    command: >
      sh -c 'test -f /app/db/database.sqlite ||
      (mkdir -p /app/db &&
       sqlite3 /app/db/database.sqlite < db/schema.sql &&
       ( [ -f db/seed.sql ] && sqlite3 /app/db/database.sqlite < db/seed.sql || true ));
      node server.js'
    ports:
      - "3002:3001"
    volumes:
      - ./db:/app/db
    environment:
      - NODE_ENV=production
    restart: unless-stopped
